---

# NOTE:
# Ports are exposed for local debugging. No components or parts of the application
# should reference localhost:${port} to access these services. Use the env var alias instead.
# i.e. postgres:5432, redis:6379

version: '3'

volumes:
  node_modules_frontend:
  node_modules_backend:

services:
  redis:
    ports:
      - 6379:6379

  postgres:
    ports:
      - 5432:5432

  frontend:
    build:
      context: ..
      dockerfile: docker/frontend/Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    volumes:
      - ${PWD}/frontend/src:/usr/src/app
      - node_modules_frontend:/usr/src/app/node_modules
    command: bash -c "yarn install && yarn run start"

  backend:
    build:
      context: ..
      dockerfile: docker/backend/Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    volumes:
      - ${PWD}/backend/src:/usr/src/app
      - node_modules_backend:/usr/src/app/node_modules
    command: bash -c "npm install && npm run babel"

  nginx:
    depends_on:
      - backend
      - frontend
    image: nginx:1.21-alpine
    restart: always
    volumes:
      - ${PWD}/docker/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
      - 8080:80
    networks:
      - application

  php:
    volumes:
      - ${PWD}/php/src:/build

  aws:
    ports:
      - "4567-4584:4567-4584"
      - 8081:8081
